sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

before_install:
  - sudo apt-get update -qq
script:
  - cd scripts
  - ./config-build.py -hc ../host-configs/linux/gnu.cmake
  - cd build-gnu-release && make
  - make test
