sudo: required
language: cpp
install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install cmake gcc-4.8 -y
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=`which g++` -DBUILD_TESTS=ON ..
        - make

script:
        - ctest
