sudo: required
language: cpp
install:
        - sudo apt-get install cmake
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=`which g++` -DBUILD_TESTS=ON ..

script:
        - ctest
