sudo: required
language: cpp
env: TRAVIS_CXX_COMPILER=g++-4.8
install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install cmake gcc-4.8 -y
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=`which g++-4.8` -DCMAKE_CXX_FLAGS="-std=c++11" -DBUILD_TESTS=ON ..
        - make VERBOSE=1

script:
        - ctest
